"""
ppt_generator.py

Render a presentation_plan.json into a PowerPoint presentation.

Pipeline:

    PDF
      |
      v
    pdf_extractor.py
      |
      v
    chunking.py
      |
      v
    presentation_ai.py
      |
      v
    presentation_plan.json
      |
      v
    ppt_generator.py
      |
      v
    PowerPoint

Responsibilities:
    1. Load the presentation plan.
    2. Load the PowerPoint template.
    3. Create slides from the AI-generated plan.
    4. Insert titles, key points, and visuals.
    5. Preserve PDF image provenance.
    6. Save the final .pptx.

Dependencies:
    pip install python-pptx
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.util import Inches, Pt


# ---------------------------------------------------------------------------
# DEFAULT PRESENTATION SETTINGS
# ---------------------------------------------------------------------------

DEFAULT_WIDTH = 13.333
DEFAULT_HEIGHT = 7.5

MARGIN_X = 0.65
TITLE_Y = 0.35
TITLE_HEIGHT = 0.65

CONTENT_Y = 1.25
CONTENT_HEIGHT = 5.55

BODY_FONT_SIZE = 22
TITLE_FONT_SIZE = 30

IMAGE_GAP = 0.30

SUPPORTED_IMAGE_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".bmp",
    ".gif",
    ".tif",
    ".tiff",
}


# ---------------------------------------------------------------------------
# FILE / JSON HELPERS
# ---------------------------------------------------------------------------

def load_json(path: str) -> Dict[str, Any]:
    """
    Load a JSON file.

    Args:
        path:
            Path to JSON file.

    Returns:
        Parsed JSON dictionary.
    """

    path = os.path.abspath(path)

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"JSON file not found: {path}"
        )

    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_presentation_plan(
    plan_path: str,
) -> Dict[str, Any]:
    """
    Load a presentation plan generated by presentation_ai.py.
    """

    plan = load_json(plan_path)

    if not isinstance(plan, dict):
        raise ValueError(
            "Presentation plan must be a JSON object."
        )

    if "slides" not in plan:
        raise ValueError(
            "Presentation plan does not contain a 'slides' field."
        )

    if not isinstance(plan["slides"], list):
        raise ValueError(
            "Presentation plan 'slides' must be a list."
        )

    return plan


# ---------------------------------------------------------------------------
# TEMPLATE HELPERS
# ---------------------------------------------------------------------------

def load_template(
    template_path: Optional[str] = None,
) -> Presentation:
    """
    Load a PowerPoint template.

    If no template is provided, create a blank presentation.

    Args:
        template_path:
            Optional .pptx/.potx file.

    Returns:
        python-pptx Presentation object.
    """

    if template_path:

        template_path = os.path.abspath(template_path)

        if not os.path.exists(template_path):
            raise FileNotFoundError(
                f"PowerPoint template not found: {template_path}"
            )

        return Presentation(template_path)

    # Blank presentation.
    prs = Presentation()

    prs.slide_width = Inches(DEFAULT_WIDTH)
    prs.slide_height = Inches(DEFAULT_HEIGHT)

    return prs


def remove_existing_slides(
    prs: Presentation,
) -> None:
    """
    Remove all existing slides from the presentation.

    This is useful when the supplied template contains example slides
    that should not appear in the final presentation.

    NOTE:
        This preserves the presentation's slide layouts/theme.
    """

    slide_ids = list(prs.slides._sldIdLst)

    for slide_id in slide_ids:

        r_id = slide_id.rId

        prs.part.drop_rel(r_id)

        prs.slides._sldIdLst.remove(slide_id)


# ---------------------------------------------------------------------------
# SLIDE LAYOUT HELPERS
# ---------------------------------------------------------------------------

def get_blank_layout(
    prs: Presentation,
):
    """
    Find the blank layout in the template.

    Falls back to the first available layout.
    """

    for layout in prs.slide_layouts:

        name = (layout.name or "").lower()

        if "blank" in name:
            return layout

    if prs.slide_layouts:
        return prs.slide_layouts[0]

    raise ValueError(
        "Presentation template contains no slide layouts."
    )


def add_blank_slide(
    prs: Presentation,
):
    """
    Add a blank slide while preserving the template's theme.
    """

    layout = get_blank_layout(prs)

    return prs.slides.add_slide(layout)


def get_slide_dimensions(
    prs: Presentation,
) -> Tuple[float, float]:
    """
    Return slide dimensions in inches.
    """

    width = prs.slide_width / 914400
    height = prs.slide_height / 914400

    return width, height


# ---------------------------------------------------------------------------
# TEXT HELPERS
# ---------------------------------------------------------------------------

def clean_text(
    text: Any,
) -> str:
    """
    Convert a value to clean display text.
    """

    if text is None:
        return ""

    return str(text).strip()


def add_text_box(
    slide,
    text: str,
    x: float,
    y: float,
    width: float,
    height: float,
    font_size: float = BODY_FONT_SIZE,
    bold: bool = False,
    align=PP_ALIGN.LEFT,
    vertical_anchor=MSO_ANCHOR.TOP,
):
    """
    Add a text box to a slide.

    Coordinates are in inches.
    """

    textbox = slide.shapes.add_textbox(
        Inches(x),
        Inches(y),
        Inches(width),
        Inches(height),
    )

    text_frame = textbox.text_frame

    text_frame.clear()

    text_frame.word_wrap = True
    text_frame.vertical_anchor = vertical_anchor

    paragraph = text_frame.paragraphs[0]

    paragraph.alignment = align

    run = paragraph.add_run()

    run.text = clean_text(text)

    run.font.size = Pt(font_size)
    run.font.bold = bold

    return textbox


def add_title(
    slide,
    title: str,
    slide_width: float,
):
    """
    Add a slide title.
    """

    return add_text_box(
        slide=slide,
        text=title,
        x=MARGIN_X,
        y=TITLE_Y,
        width=slide_width - (2 * MARGIN_X),
        height=TITLE_HEIGHT,
        font_size=TITLE_FONT_SIZE,
        bold=True,
    )


def add_bullet_list(
    slide,
    points: List[str],
    x: float,
    y: float,
    width: float,
    height: float,
    font_size: float = BODY_FONT_SIZE,
):
    """
    Add a bullet list to a slide.
    """

    textbox = slide.shapes.add_textbox(
        Inches(x),
        Inches(y),
        Inches(width),
        Inches(height),
    )

    text_frame = textbox.text_frame

    text_frame.clear()
    text_frame.word_wrap = True

    for index, point in enumerate(points):

        point = clean_text(point)

        if not point:
            continue

        if index == 0:
            paragraph = text_frame.paragraphs[0]
        else:
            paragraph = text_frame.add_paragraph()

        paragraph.text = point
        paragraph.font.size = Pt(font_size)

        paragraph.level = 0

        # python-pptx bullet behavior varies by version/theme.
        # Setting the paragraph text and level allows the template's
        # bullet formatting to be used when available.

    return textbox


# ---------------------------------------------------------------------------
# IMAGE HELPERS
# ---------------------------------------------------------------------------

def resolve_image_path(
    image: Dict[str, Any],
    plan_path: Optional[str] = None,
    image_root: Optional[str] = None,
) -> Optional[Path]:
    """
    Resolve the path to a PDF-extracted image.

    Search order:

        1. Absolute path stored in image metadata.
        2. Path relative to presentation plan.
        3. Path relative to image_root.
        4. Filename relative to image_root.
    """

    raw_path = image.get("path")

    if not raw_path:
        return None

    path = Path(raw_path)

    # Absolute path.
    if path.is_absolute() and path.exists():
        return path

    # Relative to the presentation plan.
    if plan_path:

        plan_directory = Path(plan_path).resolve().parent

        candidate = plan_directory / path

        if candidate.exists():
            return candidate

    # Relative to image root.
    if image_root:

        root = Path(image_root)

        candidate = root / path

        if candidate.exists():
            return candidate

        candidate = root / path.name

        if candidate.exists():
            return candidate

    # Relative to current working directory.
    if path.exists():
        return path.resolve()

    return None


def _image_size(
    image_path: Path,
) -> Tuple[int, int]:
    """
    Get image dimensions.

    Uses Pillow when available.

    Falls back to (1, 1) so the image can still be inserted.
    """

    try:
        from PIL import Image

        with Image.open(image_path) as img:
            return img.size

    except Exception:
        return 1, 1


def add_image_contain(
    slide,
    image_path: Path,
    x: float,
    y: float,
    width: float,
    height: float,
):
    """
    Add an image while preserving its aspect ratio.

    The entire image fits inside the supplied rectangle.
    """

    image_width, image_height = _image_size(
        image_path
    )

    if image_width <= 0 or image_height <= 0:
        return None

    image_ratio = image_width / image_height
    box_ratio = width / height

    if image_ratio > box_ratio:

        # Image is relatively wide.
        final_width = width
        final_height = width / image_ratio

        final_x = x
        final_y = y + (height - final_height) / 2

    else:

        # Image is relatively tall.
        final_height = height
        final_width = height * image_ratio

        final_x = x + (width - final_width) / 2
        final_y = y

    return slide.shapes.add_picture(
        str(image_path),
        Inches(final_x),
        Inches(final_y),
        width=Inches(final_width),
        height=Inches(final_height),
    )


def add_image_cover(
    slide,
    image_path: Path,
    x: float,
    y: float,
    width: float,
    height: float,
):
    """
    Add an image filling the supplied rectangle.

    The image is cropped as necessary to preserve aspect ratio.

    This is useful for photographic visuals.
    """

    image_width, image_height = _image_size(
        image_path
    )

    if image_width <= 0 or image_height <= 0:
        return None

    image_ratio = image_width / image_height
    box_ratio = width / height

    if image_ratio > box_ratio:

        # Image is too wide.
        final_height = height
        final_width = height * image_ratio

        final_x = x - (final_width - width) / 2
        final_y = y

    else:

        # Image is too tall.
        final_width = width
        final_height = width / image_ratio

        final_x = x
        final_y = y - (final_height - height) / 2

    return slide.shapes.add_picture(
        str(image_path),
        Inches(final_x),
        Inches(final_y),
        width=Inches(final_width),
        height=Inches(final_height),
    )


# ---------------------------------------------------------------------------
# IMAGE LOOKUP
# ---------------------------------------------------------------------------

def build_image_catalog(
    plan: Dict[str, Any],
) -> Dict[str, Dict[str, Any]]:
    """
    Build an image lookup table.

    Expected presentation plan format:

        {
            "images": [
                {
                    "image_id": "...",
                    "path": "...",
                    ...
                }
            ]
        }

    Also supports images nested under a document object.
    """

    images = plan.get("images", [])

    if not images:

        document = plan.get("document", {})

        if isinstance(document, dict):
            images = document.get("images", [])

    catalog = {}

    for image in images:

        if not isinstance(image, dict):
            continue

        image_id = image.get("image_id")

        if image_id:
            catalog[str(image_id)] = image

    return catalog


def find_visual_for_slide(
    visual: Any,
    image_catalog: Dict[str, Dict[str, Any]],
) -> Optional[Dict[str, Any]]:
    """
    Resolve a visual reference from the AI presentation plan.

    Supports:

        "page_4_image_1"

    or:

        {
            "image_id": "page_4_image_1",
            "reason": "..."
        }
    """

    if isinstance(visual, str):

        return image_catalog.get(visual)

    if isinstance(visual, dict):

        image_id = (
            visual.get("image_id")
            or visual.get("id")
        )

        if image_id:
            return image_catalog.get(str(image_id))

    return None


# ---------------------------------------------------------------------------
# SLIDE CONTENT EXTRACTION
# ---------------------------------------------------------------------------

def get_slide_title(
    slide_plan: Dict[str, Any],
) -> str:
    """
    Get the slide title from a slide plan.
    """

    return clean_text(
        slide_plan.get("title")
        or slide_plan.get("slide_title")
        or f"Slide {slide_plan.get('slide_number', '')}"
    )


def get_slide_points(
    slide_plan: Dict[str, Any],
) -> List[str]:
    """
    Get the main bullet/key-point content.
    """

    points = (
        slide_plan.get("key_points")
        or slide_plan.get("bullet_points")
        or slide_plan.get("points")
        or []
    )

    if isinstance(points, str):
        return [points]

    return [
        clean_text(point)
        for point in points
        if clean_text(point)
    ]


def get_slide_visuals(
    slide_plan: Dict[str, Any],
) -> List[Any]:
    """
    Get visual references from a slide plan.
    """

    visuals = (
        slide_plan.get("visuals")
        or slide_plan.get("images")
        or []
    )

    if isinstance(visuals, (str, dict)):
        visuals = [visuals]

    return visuals


# ---------------------------------------------------------------------------
# SLIDE TYPE DETECTION
# ---------------------------------------------------------------------------

def get_slide_type(
    slide_plan: Dict[str, Any],
) -> str:
    """
    Determine how a slide should be rendered.

    Supported types:

        title
        content
        visual
        two_column
        quote
        section
    """

    slide_type = slide_plan.get("slide_type")

    if slide_type:
        return str(slide_type).lower()

    # Backward-compatible aliases.
    slide_type = slide_plan.get("layout")

    if slide_type:
        return str(slide_type).lower()

    # Infer a reasonable default.
    visuals = get_slide_visuals(slide_plan)
    points = get_slide_points(slide_plan)

    if visuals and not points:
        return "visual"

    return "content"


# ---------------------------------------------------------------------------
# SLIDE RENDERERS
# ---------------------------------------------------------------------------

def render_title_slide(
    prs: Presentation,
    slide_plan: Dict[str, Any],
):
    """
    Render a title slide.
    """

    slide = add_blank_slide(prs)

    slide_width, slide_height = get_slide_dimensions(prs)

    title = get_slide_title(slide_plan)

    subtitle = clean_text(
        slide_plan.get("subtitle")
        or slide_plan.get("description")
        or ""
    )

    add_text_box(
        slide=slide,
        text=title,
        x=1.0,
        y=2.25,
        width=slide_width - 2.0,
        height=1.2,
        font_size=40,
        bold=True,
        align=PP_ALIGN.CENTER,
        vertical_anchor=MSO_ANCHOR.MIDDLE,
    )

    if subtitle:

        add_text_box(
            slide=slide,
            text=subtitle,
            x=1.5,
            y=3.65,
            width=slide_width - 3.0,
            height=1.0,
            font_size=22,
            align=PP_ALIGN.CENTER,
        )

    return slide


def render_content_slide(
    prs: Presentation,
    slide_plan: Dict[str, Any],
    image_catalog: Dict[str, Dict[str, Any]],
    plan_path: str,
    image_root: Optional[str] = None,
):
    """
    Render a standard content slide.

    Layout:

        -------------------------
        Title
        -------------------------
        • Point
        • Point        Image
        • Point        Image
        -------------------------
    """

    slide = add_blank_slide(prs)

    slide_width, slide_height = get_slide_dimensions(prs)

    title = get_slide_title(slide_plan)

    points = get_slide_points(slide_plan)

    visuals = get_slide_visuals(slide_plan)

    add_title(
        slide,
        title,
        slide_width,
    )

    # ---------------------------------------------------------------
    # No visuals.
    # ---------------------------------------------------------------

    if not visuals:

        add_bullet_list(
            slide=slide,
            points=points,
            x=MARGIN_X,
            y=CONTENT_Y,
            width=slide_width - (2 * MARGIN_X),
            height=CONTENT_HEIGHT,
        )

        return slide

    # ---------------------------------------------------------------
    # Visuals present.
    #
    # Text gets approximately 55% of the slide.
    # Visual gets approximately 40%.
    # ---------------------------------------------------------------

    text_width = slide_width * 0.53

    image_x = (
        MARGIN_X +
        text_width +
        IMAGE_GAP
    )

    image_width = (
        slide_width -
        image_x -
        MARGIN_X
    )

    if points:

        add_bullet_list(
            slide=slide,
            points=points,
            x=MARGIN_X,
            y=CONTENT_Y,
            width=text_width,
            height=CONTENT_HEIGHT,
        )

    # Use first useful visual.
    for visual in visuals:

        image_info = find_visual_for_slide(
            visual,
            image_catalog,
        )

        if not image_info:
            continue

        image_path = resolve_image_path(
            image_info,
            plan_path=plan_path,
            image_root=image_root,
        )

        if not image_path:
            continue

        add_image_contain(
            slide=slide,
            image_path=image_path,
            x=image_x,
            y=CONTENT_Y,
            width=image_width,
            height=CONTENT_HEIGHT,
        )

        break

    return slide


def render_visual_slide(
    prs: Presentation,
    slide_plan: Dict[str, Any],
    image_catalog: Dict[str, Dict[str, Any]],
    plan_path: str,
    image_root: Optional[str] = None,
):
    """
    Render a visual-focused slide.

    The selected PDF image occupies most of the slide.
    """

    slide = add_blank_slide(prs)

    slide_width, slide_height = get_slide_dimensions(prs)

    title = get_slide_title(slide_plan)

    add_title(
        slide,
        title,
        slide_width,
    )

    visuals = get_slide_visuals(slide_plan)

    for visual in visuals:

        image_info = find_visual_for_slide(
            visual,
            image_catalog,
        )

        if not image_info:
            continue

        image_path = resolve_image_path(
            image_info,
            plan_path=plan_path,
            image_root=image_root,
        )

        if not image_path:
            continue

        add_image_contain(
            slide=slide,
            image_path=image_path,
            x=1.0,
            y=1.25,
            width=slide_width - 2.0,
            height=5.6,
        )

        break

    return slide


def render_two_column_slide(
    prs: Presentation,
    slide_plan: Dict[str, Any],
):
    """
    Render a two-column text slide.

    Expected optional structure:

        {
            "left_title": "...",
            "left_points": [...],
            "right_title": "...",
            "right_points": [...]
        }
    """

    slide = add_blank_slide(prs)

    slide_width, slide_height = get_slide_dimensions(prs)

    add_title(
        slide,
        get_slide_title(slide_plan),
        slide_width,
    )

    left_title = clean_text(
        slide_plan.get("left_title")
        or ""
    )

    right_title = clean_text(
        slide_plan.get("right_title")
        or ""
    )

    left_points = slide_plan.get(
        "left_points",
        [],
    )

    right_points = slide_plan.get(
        "right_points",
        [],
    )

    column_width = (
        slide_width -
        (2 * MARGIN_X) -
        IMAGE_GAP
    ) / 2

    left_x = MARGIN_X

    right_x = (
        MARGIN_X +
        column_width +
        IMAGE_GAP
    )

    if left_title:

        add_text_box(
            slide=slide,
            text=left_title,
            x=left_x,
            y=CONTENT_Y,
            width=column_width,
            height=0.45,
            font_size=22,
            bold=True,
        )

    if right_title:

        add_text_box(
            slide=slide,
            text=right_title,
            x=right_x,
            y=CONTENT_Y,
            width=column_width,
            height=0.45,
            font_size=22,
            bold=True,
        )

    add_bullet_list(
        slide=slide,
        points=left_points,
        x=left_x,
        y=CONTENT_Y + 0.55,
        width=column_width,
        height=CONTENT_HEIGHT - 0.55,
    )

    add_bullet_list(
        slide=slide,
        points=right_points,
        x=right_x,
        y=CONTENT_Y + 0.55,
        width=column_width,
        height=CONTENT_HEIGHT - 0.55,
    )

    return slide


def render_quote_slide(
    prs: Presentation,
    slide_plan: Dict[str, Any],
):
    """
    Render a quote/highlight slide.
    """

    slide = add_blank_slide(prs)

    slide_width, slide_height = get_slide_dimensions(prs)

    title = get_slide_title(slide_plan)

    quote = clean_text(
        slide_plan.get("quote")
        or slide_plan.get("text")
        or ""
    )

    attribution = clean_text(
        slide_plan.get("attribution")
        or slide_plan.get("source")
        or ""
    )

    add_title(
        slide,
        title,
        slide_width,
    )

    add_text_box(
        slide=slide,
        text=quote,
        x=1.3,
        y=2.0,
        width=slide_width - 2.6,
        height=2.7,
        font_size=32,
        bold=False,
        align=PP_ALIGN.CENTER,
        vertical_anchor=MSO_ANCHOR.MIDDLE,
    )

    if attribution:

        add_text_box(
            slide=slide,
            text=attribution,
            x=2.0,
            y=5.0,
            width=slide_width - 4.0,
            height=0.6,
            font_size=18,
            align=PP_ALIGN.CENTER,
        )

    return slide


def render_section_slide(
    prs: Presentation,
    slide_plan: Dict[str, Any],
):
    """
    Render a section-divider slide.
    """

    slide = add_blank_slide(prs)

    slide_width, slide_height = get_slide_dimensions(prs)

    title = get_slide_title(slide_plan)

    description = clean_text(
        slide_plan.get("description")
        or ""
    )

    add_text_box(
        slide=slide,
        text=title,
        x=1.0,
        y=2.65,
        width=slide_width - 2.0,
        height=1.0,
        font_size=38,
        bold=True,
        align=PP_ALIGN.CENTER,
        vertical_anchor=MSO_ANCHOR.MIDDLE,
    )

    if description:

        add_text_box(
            slide=slide,
            text=description,
            x=1.5,
            y=3.8,
            width=slide_width - 3.0,
            height=1.0,
            font_size=20,
            align=PP_ALIGN.CENTER,
        )

    return slide


# ---------------------------------------------------------------------------
# MAIN SLIDE RENDERER
# ---------------------------------------------------------------------------

def render_slide(
    prs: Presentation,
    slide_plan: Dict[str, Any],
    image_catalog: Dict[str, Dict[str, Any]],
    plan_path: str,
    image_root: Optional[str] = None,
):
    """
    Render one slide based on its slide_type.
    """

    slide_type = get_slide_type(
        slide_plan
    )

    if slide_type in {
        "title",
        "title_slide",
    }:

        return render_title_slide(
            prs,
            slide_plan,
        )

    if slide_type in {
        "visual",
        "image",
        "visual_focus",
    }:

        return render_visual_slide(
            prs,
            slide_plan,
            image_catalog,
            plan_path,
            image_root,
        )

    if slide_type in {
        "two_column",
        "two-column",
        "comparison",
    }:

        return render_two_column_slide(
            prs,
            slide_plan,
        )

    if slide_type in {
        "quote",
        "highlight",
    }:

        return render_quote_slide(
            prs,
            slide_plan,
        )

    if slide_type in {
        "section",
        "section_divider",
        "divider",
    }:

        return render_section_slide(
            prs,
            slide_plan,
        )

    # Default.
    return render_content_slide(
        prs,
        slide_plan,
        image_catalog,
        plan_path,
        image_root,
    )


# ---------------------------------------------------------------------------
# PRESENTATION VALIDATION
# ---------------------------------------------------------------------------

def validate_plan_for_generation(
    plan: Dict[str, Any],
) -> List[str]:
    """
    Validate the minimum information needed to generate slides.

    Returns:
        List of warnings/errors.
    """

    problems = []

    slides = plan.get("slides")

    if not isinstance(slides, list):
        problems.append(
            "Presentation plan does not contain a valid slides list."
        )

        return problems

    if len(slides) == 0:
        problems.append(
            "Presentation plan contains no slides."
        )

    for index, slide in enumerate(slides, start=1):

        if not isinstance(slide, dict):

            problems.append(
                f"Slide {index} is not a JSON object."
            )

            continue

        if not get_slide_title(slide):

            problems.append(
                f"Slide {index} has no title."
            )

    return problems


# ---------------------------------------------------------------------------
# GENERATE PRESENTATION
# ---------------------------------------------------------------------------

def generate_presentation(
    plan_path: str,
    output_path: str,
    template_path: Optional[str] = None,
    image_root: Optional[str] = None,
    clear_template_slides: bool = True,
) -> str:
    """
    Generate a PowerPoint from a presentation plan.

    Args:
        plan_path:
            Path to presentation_plan.json.

        output_path:
            Destination .pptx path.

        template_path:
            Optional PowerPoint template.

        image_root:
            Optional root directory containing extracted images.

        clear_template_slides:
            If True, remove example/content slides from the template
            before generating the presentation.

    Returns:
        Absolute path to generated PowerPoint.
    """

    plan_path = os.path.abspath(plan_path)

    output_path = os.path.abspath(output_path)

    # ---------------------------------------------------------------
    # Load plan.
    # ---------------------------------------------------------------

    plan = load_presentation_plan(
        plan_path
    )

    # ---------------------------------------------------------------
    # Validate plan.
    # ---------------------------------------------------------------

    problems = validate_plan_for_generation(
        plan
    )

    if problems:

        for problem in problems:
            print(f"Warning: {problem}")

    # ---------------------------------------------------------------
    # Load PowerPoint template.
    # ---------------------------------------------------------------

    prs = load_template(
        template_path
    )

    # ---------------------------------------------------------------
    # Remove template example slides if requested.
    # ---------------------------------------------------------------

    if clear_template_slides:
        remove_existing_slides(prs)

    # ---------------------------------------------------------------
    # Build image lookup.
    # ---------------------------------------------------------------

    image_catalog = build_image_catalog(
        plan
    )

    # ---------------------------------------------------------------
    # Generate slides.
    # ---------------------------------------------------------------

    slides = plan["slides"]

    print(
        f"Generating {len(slides)} slides..."
    )

    for index, slide_plan in enumerate(
        slides,
        start=1,
    ):

        if not isinstance(slide_plan, dict):

            print(
                f"Warning: Skipping invalid slide {index}."
            )

            continue

        try:

            render_slide(
                prs=prs,
                slide_plan=slide_plan,
                image_catalog=image_catalog,
                plan_path=plan_path,
                image_root=image_root,
            )

            print(
                f"  Created slide {index}: "
                f"{get_slide_title(slide_plan)}"
            )

        except Exception as exc:

            print(
                f"Warning: Could not render slide "
                f"{index}: {exc}"
            )

    # ---------------------------------------------------------------
    # Ensure output directory exists.
    # ---------------------------------------------------------------

    output_directory = Path(
        output_path
    ).parent

    output_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ---------------------------------------------------------------
    # Save presentation.
    # ---------------------------------------------------------------

    prs.save(output_path)

    print(
        f"\nPresentation saved to:\n"
        f"{output_path}"
    )

    return output_path


# ---------------------------------------------------------------------------
# COMMAND LINE INTERFACE
# ---------------------------------------------------------------------------

def main():
    """
    Command-line interface.

    Example:

        python ppt_generator.py \
            presentation_plan.json \
            output.pptx \
            --template template.pptx \
            --image-root images/
    """

    parser = argparse.ArgumentParser(
        description=(
            "Generate a PowerPoint presentation from "
            "presentation_plan.json."
        )
    )

    parser.add_argument(
        "plan",
        help="Path to presentation_plan.json",
    )

    parser.add_argument(
        "output",
        help="Path for generated .pptx",
    )

    parser.add_argument(
        "--template",
        default=None,
        help="Optional PowerPoint template (.pptx/.potx)",
    )

    parser.add_argument(
        "--image-root",
        default=None,
        help=(
            "Optional root directory containing "
            "extracted PDF images."
        ),
    )

    parser.add_argument(
        "--keep-template-slides",
        action="store_true",
        help=(
            "Keep existing slides from the PowerPoint template."
        ),
    )

    args = parser.parse_args()

    generate_presentation(
        plan_path=args.plan,
        output_path=args.output,
        template_path=args.template,
        image_root=args.image_root,
        clear_template_slides=not args.keep_template_slides,
    )


if __name__ == "__main__":
    main()